### ISSUE TITLE
JNML Install tutorial

### ISSUE THREAD

**Issue by joebowen** [openworm/hodgkin_huxley_tutorial#1]
Create JNML install tutorial.

**Comment by slarson** [comment]
cc: @wilzh40

**Comment by wilzh40** [comment]
I just made a fresh install of ubuntu linux and fully upgraded everything. Could you please repost the travis.yml file you referenced? I remember installed it the hard way manually using the development branch, and compiling using maven.

**Comment by joebowen** [comment]
https://github.com/openworm/muscle_model/blob/master/.travis.yml

**Comment by pgleeson** [comment]
Ideally the instructions for installing jNeuroML should reside here: https://github.com/NeuroML/jNeuroML/blob/master/README.md. Happy for suggestions for additions to that if it's incomplete/unclear.

Alternatively if this issue relates to installing the environment for running the tests etc. related to the muscle model, then a link to the (commented) .travis.yml file above is the most appropriate, as locations for the utilities in BlueBrainProjectShowcase etc. will change and this script will be updated accordingly.

**Comment by pgleeson** [comment]
Simplest thing might be to bundle a copy of the jNeuroML jar with this repo? Latest is available here: http://sourceforge.net/p/neuroml/code/HEAD/tree/jNeuroMLJar/. It's ~18M, but with a local [run.sh](https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/run.sh) (and run.bat) pointing at it, it would mean no other installation requirements for running the NML2 version...

**Comment by pgleeson** [comment]
Fixed, as the jnml jar has been added to the repo
