### ISSUE TITLE
Automatic update of ReadTheDocs?

### ISSUE THREAD

**Issue by pgleeson** [openworm/hodgkin_huxley_tutorial#13]
Shouldn't the [Readthedocs page](http://hodgkin-huxley-tutorial.readthedocs.org/en/latest/) be automatically updated every time there's a commit to master?

Last update to the docs seems to have been a commit by @travs in June...

**Comment by joebowen** [comment]
Do I still have control over that readthedocs project?  If so, I'll take a
look at what's going on when I get home tonight.

Joe

**Comment by pgleeson** [comment]
@joebowen Thanks!

**Comment by joebowen** [comment]
I went ahead and kicked off a build manually.  I went to look into why it wasn't building automatically and I'm not sure.  [This site mentions how to configure auto-update](http://read-the-docs.readthedocs.org/en/latest/webhooks.html#github) but according to the directions, it's already setup properly.  I went ahead and updated the service in GitHub but it was already activated so not sure if that will help or not.  I guess we'll have to keep an eye on it and make sure it's now auto updating again.

**Comment by joebowen** [comment]
Also, I might not be the only one who is an owner of this project.  It looks like @slarson and @travs also have ownership.

**Comment by pgleeson** [comment]
There is still an issue with updating the live site... It has updated from your rebuild last night, but it not showing today’s changes. I removed the GitHub webhook on the project and re added it.

I've added a page today describing some exercises that can be done with the HH model (python or nml2 versions): https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/_static/Exercises.rst. If you could do another manual build @joebowen I'd be grateful, and then at least this page will show up on readthedocs.

**Comment by joebowen** [comment]
@pgleeson I'm working from home today, so just ping me when you're ready and I'll do a manual build.

**Comment by pgleeson** [comment]
Thanks. Ready to go as is. 

I've also updated the intro: https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/index.rst to reflect that this will be both a HH model tutorial as well as a guide to implementing it in Python/NML2. Hope this is ok.

**Comment by joebowen** [comment]
Built, and that's ok with me, best that the current title accurately reflect the contents.

**Comment by pgleeson** [comment]
Thanks @joebowen.

**Comment by pgleeson** [comment]
This is fixed now. It required an explicit webhook to http://readthedocs.org/build/hodgkin-huxley-tutorial under [Webhooks](https://github.com/openworm/hodgkin_huxley_tutorial/settings/hooks), rather than one under [Integrations and services](https://github.com/openworm/hodgkin_huxley_tutorial/settings/installations), since the HH tutorial seems to have been set up on readthedocs.org as a standalone Git repo, rather than integrated with GitHub.
