### ISSUE TITLE
Create a Jupyter Notebook of the pure Python HH example 

### ISSUE THREAD

**Issue by pgleeson** [openworm/hodgkin_huxley_tutorial#19]
Based on https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/HodgkinHuxley.py

It may be best to reuse the python script, just importing it into the notebook and running simulations, generating plots, changing variables etc. in the notebook itself (keeps the display of code in the notebook minimal). 

The Python class could be supplemented with methods for helping to print the state of the cell model (conductances, current injection settings etc) which would aid understanding of the current configuration being simulated. 

Some of the exercises in https://hodgkin-huxley-tutorial.readthedocs.io/en/latest/_static/Exercises.html could be added with pointers to which variables to change.

**Comment by pgleeson** [comment]
@irahulsonkar

**Comment by irahulsonkar** [comment]
> @irahulsonkar

Thanks @pgleeson,
I will work on this issue.

**Comment by pgleeson** [comment]
Merged to master! Thanks @irahulsonkar
