### ISSUE TITLE
Create Jupyter notebook for NeuroML model

### ISSUE THREAD

**Issue by pgleeson** [openworm/hodgkin_huxley_tutorial#20]
Similar to #19, make a similar notebook which uses as the underlying model the NeuroML version. It would probably require making a helper class which allows easy loading/editing/simulating of the NML model, and returning results.

**Comment by sanjayankur31** [comment]
This is the NeuroML tutorial on this (aimed to teach people NeuroML):

https://docs.neuroml.org/Userdocs/SingleCompartmentHHExample.html

**Comment by sanjayankur31** [comment]
@irahulsonkar

**Comment by irahulsonkar** [comment]
> @irahulsonkar

Thanks @sanjayankur31,
Will move to this after HH model #19

**Comment by irahulsonkar** [comment]
@pgleeson @sanjayankur31 
Notebook based on `info` method added in PR #43

**Comment by pgleeson** [comment]
Added.
