### ISSUE TITLE
Adding certain initial values to simulation

### ISSUE THREAD

**Issue by joebowen** [openworm/hodgkin_huxley_tutorial#4]
Where do the rest of these initial values from HodgkinHuxley.py fit into the NeuroML/LEMS Model?

http://hodgkin-huxley-tutorial.readthedocs.org/en/latest/_static/Tutorial.html#initial-values

**Comment by slarson** [comment]
I've also added some text for this in #5 -- check it out.  @pgleeson suggested the text initially, and I modified what's there from his email.

**Comment by joebowen** [comment]
This seems reasonable, I'm going to close it for now.
