### ISSUE TITLE
Update line numbers 

### ISSUE THREAD

**Issue by pgleeson** [openworm/hodgkin_huxley_tutorial#40]
The updated HodgkinHuxley.py has shifted some of the line numbers of different parts of the code so this:
https://hodgkin-huxley-tutorial.readthedocs.io/en/latest/_toc/Tutorial.html#running-the-model-implementations 
should be rechecked and https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/_toc/Tutorial.rst updated

**Comment by irahulsonkar** [comment]
@pgleeson 
Fixed this in PR #44.

**Comment by pgleeson** [comment]
Fixed
