### ISSUE TITLE
Error running HodgkinHuxley.py

### ISSUE THREAD

**Issue by travs** [openworm/hodgkin_huxley_tutorial#7]
When I run `python HodgkinHuxley.py` I get this error:

```
└─▪ python HodgkinHuxley.py
Traceback (most recent call last):
  File "HodgkinHuxley.py", line 164, in <module>
    runner.Main()
  File "HodgkinHuxley.py", line 133, in Main
    plt.figure()
AttributeError: 'module' object has no attribute 'figure'
```

`plt` is standing in for the `pylab` import, so when I do an interactive session and try `import pylab; pylab.figure()`, I get the same error.

@slarson

**Comment by slarson** [comment]
[Seems relevant](https://stackoverflow.com/questions/16109039/attributeerror-module-object-has-no-attribute)

**Comment by pgleeson** [comment]
Looks like more of an issue with your local install of matplotlib... Maybe related to https://github.com/pgleeson/neurotune/issues/1?

This example works fine for me.

**Comment by travs** [comment]
After looking at [the SO answer](https://stackoverflow.com/questions/16109039/attributeerror-module-object-has-no-attribute) I was able to get it to work. 

Just changing [this import](https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/HodgkinHuxley.py#L2) to `import matplotlib.pyplot as plt`

**Comment by travs** [comment]
@pgleeson what version of matplotlib are you using? I have `1.4.3`

**Comment by pgleeson** [comment]
I'm using 1.3.1, but I believe the core api for it is quite stable...

**Comment by travs** [comment]
After running this in a fresh venv I was able to get it to work
