### ISSUE TITLE
Issue with multiple plot axes/ticks in HH jupyter notebook on matplotlib 3.8

### ISSUE THREAD

**Issue by pgleeson** [openworm/hodgkin_huxley_tutorial#70]
Issue with matplotlib 3.8.0 not 3.5.1
Basically plotting another axis around all others..?

![Screenshot 2023-10-19 at 15 58 57](https://github.com/openworm/hodgkin_huxley_tutorial/assets/1556687/88a1a256-be36-4cc3-9cd1-7d19a5e3589c)

**Comment by pgleeson** [comment]
Not an issue with matplotlib 3.7...

Simplest to reproduce by running https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/HodgkinHuxley.py

**Comment by sanjayankur31** [comment]
Nothing jumps out from the changelog, will need some digging into:


https://matplotlib.org/devdocs/users/prev_whats_new/whats_new_3.8.0.html
